spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: lb://productt
          predicates:
            - Path=/api/categories/**,/api/products/**,/api/reviews/**,/api/carts/**,/api/orders/**,/api/order-items/**
          filters:
            - StripPrefix=1
        - id: user-service
          uri: lb://userss
          predicates:
              - Path=/api/user/**

          filters:
              - StripPrefix=1


    loadbalancer:
      ribbon:
        enabled: false